---
title: "The Effects of Work and Lifestyle on Diagnosis of Diabetes"
author: "Group 12"
date: "2020-10-19"
output: pdf_document
---



<div id="chae-bae-pritam-sinha-chen-hao-yu" class="section level1">
<h1>Chae Bae, Pritam Sinha, Chen Hao Yu</h1>
</div>
<div id="october-18-2020" class="section level1">
<h1>October 18, 2020</h1>
<p>Github repository: <a href="https://github.com/JosephYuGithub/Effects-of-Work-and-Lifestyle-on-Diabetes/tree/main/content/post" class="uri">https://github.com/JosephYuGithub/Effects-of-Work-and-Lifestyle-on-Diabetes/tree/main/content/post</a></p>
<div id="abstract" class="section level2">
<h2>Abstract</h2>
<p>Out paper is designed to look at the effects of work and lifestyle on the age at which the recipients of the General Social Survey (GSS) are diagnosed with diabetes. Our model will look at a select few variables and attempt to create regression models based on these variables to predict the age at which someone will be diagnosed with diabetes. We have found that individuals who are have longer sleep hours are more likely to be diagnosed with diabetes at an earlier age, and shorter working hours tend to correlate with a earlier diagnoses as well. However, income levels and alcohol consumption on the other hand do not appear to affect the age of diagnosis of diabetes.</p>
</div>
<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p>According to the World Health Organization (2020), diabetes is quickly on the rise with 422 million people diagnosed with the condition in 2014, up from 108 million in 1980. Adults with diabetes are more likely to be at risk of heart attacks and strokes, and if conditions worsen, could lead to limb amputations and blindness. (WHO, 2020) Diabetes sits as the 9th deadliest illness in the world at a staggering death toll of 1.37 million in 2017, that is more than HIV/AIDS and malaria! (Ritchie, 2018)</p>
<p>Currently, diabetes is tested and diagnosed through blood sugar tests, and can be treated through regular monitoring of blood sugar, medication, healthy diet, and regular exercise (Mayo Clinic, 2020). Therefore, it is imperative that individuals are properly tested for diabetes as soon as possible to avoid worsening conditions. Our study is to establish any correlations between the hours of sleep, working hours, income levels, and alcohol consumption to better predict the age of diagnosis of diabetes. Do individuals with shorter sleep hours tend to be diagnosed with diabetes earlier than individuals who sleep longer? Does alcohol consumption have an effect on the age of diagnosis. Our study will attempt to answer those questions.</p>
<p>Lastly, I will be mentioning the R libraries used to clean and model our data. The tidyverse library is an extensive collection of different libraries used commonly in statistical work. In this study, we will be using primarily the dplyr library and the ggplot2 library, both part of the tidyverse collection. The dplyr library is a useful collection that allows us to clean the dataset. We can subset variables using the select function, create new columns using the mutate function, rename column names from their original titles in the GSS survey to more appropriate and descriptive names with the rename function, and group row operations using rowwise. The ggplot2 library allows us to map out our models with a variety of different options, in this study we will be only using a scatterplot using geom_point. Additionally, the janitor library will be used for the clean_names function, which will help us return names in lowercase form, and substitute spaces with underscores.</p>
</div>
<div id="data" class="section level2">
<h2>Data</h2>
<pre><code>## # A tibble: 66 x 6
##    case_id income_12months age_first_diagn… sleep_hours average_drink_f…
##      &lt;dbl&gt; &lt;chr&gt;                      &lt;dbl&gt;       &lt;dbl&gt; &lt;chr&gt;           
##  1    1809 $10,000 to 14,…               55           6 Once or twice a…
##  2    2014 $20,000 to 29,…                1           7 Less often than…
##  3    2136 $40,000 to 59,…               14           7 2 - 3 times a w…
##  4    2833 $20,000 to 29,…               25           7 2 - 3 times a w…
##  5    3193 $40,000 to 59,…               11           8 Once a week     
##  6    4341 $20,000 to 29,…               24           8 Once a week     
##  7    4585 $40,000 to 59,…               42           6 Once a week     
##  8    5540 $5,000 to 9,999               45           6 Once or twice a…
##  9    6078 Less than $5,0…                4           8 Less often than…
## 10    6163 $5,000 to 9,999               50           7 Once a week     
## # … with 56 more rows, and 1 more variable: work_hours_per_week &lt;dbl&gt;</code></pre>
<p>The data was retrieved from GSS, and 66 observations were left after cleaning the data.</p>
</div>
<div id="model" class="section level2">
<h2>Model</h2>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/The_Effects_of_Work_and_Lifestyle_on_the_Diagnosis_of_Diabetes_files/figure-html/unnamed-chunk-4-1.png" width="672" /></p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/The_Effects_of_Work_and_Lifestyle_on_the_Diagnosis_of_Diabetes_files/figure-html/unnamed-chunk-4-2.png" width="672" /></p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/The_Effects_of_Work_and_Lifestyle_on_the_Diagnosis_of_Diabetes_files/figure-html/unnamed-chunk-4-3.png" width="672" /></p>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/post/The_Effects_of_Work_and_Lifestyle_on_the_Diagnosis_of_Diabetes_files/figure-html/unnamed-chunk-4-4.png" width="672" /></p>
<pre><code>## 
## Call:
## lm(formula = age_first_diagnosed_with_diabetes ~ sleep_hours, 
##     data = health_linear)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -32.493 -19.378   3.817  16.007  31.507 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   57.711     13.576   4.251 7.06e-05 ***
## sleep_hours   -3.460      1.914  -1.807   0.0754 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.05 on 64 degrees of freedom
## Multiple R-squared:  0.04855,    Adjusted R-squared:  0.03369 
## F-statistic: 3.266 on 1 and 64 DF,  p-value: 0.07544</code></pre>
<p>The linear regression model for <span class="math inline">\(\hat{Y}\)</span> = 57.71 - 3.46*Sleep Hours, where <span class="math inline">\(\hat{Y}\)</span> is the expected age first diagnosed with diabetes.</p>
<pre><code>## 
## Call:
## lm(formula = age_first_diagnosed_with_diabetes ~ work_hours_per_week, 
##     data = health_linear)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -33.07 -18.10   3.21  15.33  34.06 
## 
## Coefficients:
##                     Estimate Std. Error t value Pr(&gt;|t|)   
## (Intercept)          21.4074     7.4934   2.857  0.00576 **
## work_hours_per_week   0.3176     0.1862   1.706  0.09287 . 
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.1 on 64 degrees of freedom
## Multiple R-squared:  0.0435, Adjusted R-squared:  0.02855 
## F-statistic:  2.91 on 1 and 64 DF,  p-value: 0.09287</code></pre>
<p>The linear regression model for <span class="math inline">\(\hat{Y}\)</span> = 21.41 - 0.32*Hours spent working per week, where <span class="math inline">\(\hat{Y}\)</span> is the expected age first diagnosed with diabetes.</p>
<pre><code>## 
## Call:
## lm(formula = age_first_diagnosed_with_diabetes ~ income_12months, 
##     data = health_linear)
## 
## Residuals:
##    Min     1Q Median     3Q    Max 
## -37.18 -15.13   4.09  13.77  35.33 
## 
## Coefficients:
##                                  Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)                       37.5000     6.8586   5.468 1.01e-06 ***
## income_12months$15,000 to 19,999  -4.5000     9.6995  -0.464   0.6444    
## income_12months$20,000 to 29,999   0.6818     9.0139   0.076   0.9400    
## income_12months$30,000 to 39,999  -4.3750     9.6995  -0.451   0.6536    
## income_12months$40,000 to 59,999  -4.3462     8.7171  -0.499   0.6200    
## income_12months$5,000 to 9,999    -6.0556     9.4262  -0.642   0.5231    
## income_12months$60,000 to 79,999  10.8333    13.1331   0.825   0.4128    
## income_12monthsLess than $5,000  -19.8333    10.4766  -1.893   0.0633 .  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.4 on 58 degrees of freedom
## Multiple R-squared:  0.1056, Adjusted R-squared:  -0.002389 
## F-statistic: 0.9779 on 7 and 58 DF,  p-value: 0.4561</code></pre>
<p>The multiple linear regression model for <span class="math inline">\(\hat{Y}\)</span> = 37.5 - 4.5 * (Personal Income of $15,000 to $19,999) + 0.68 * (Personal Income of $20,000 to $29,999) - 4.37 * (Personal Income of $30,000 to $39,999) - 4.34 * (Personal Income of $40,000 to $59,999) - 6.06 * (Personal Income of $5,000 to $9,999) + 10.83 * (Personal Income of $60,000 to $79,999) - 19.83 * (Personal Income of Less than $5,000), where <span class="math inline">\(\hat{Y}\)</span> is the expected age first diagnosed with diabetes.</p>
<pre><code>## 
## Call:
## lm(formula = age_first_diagnosed_with_diabetes ~ average_drink_for_12_months, 
##     data = health_linear)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -31.750 -16.712   2.792  15.037  32.250 
## 
## Coefficients:
##                                                         Estimate Std. Error
## (Intercept)                                               30.600      6.216
## average_drink_for_12_months4 - 6 times a week             14.067     12.941
## average_drink_for_12_monthsEvery day                      17.400     12.941
## average_drink_for_12_monthsLess often than once a month    2.150      7.399
## average_drink_for_12_monthsOnce a week                    -0.850      9.325
## average_drink_for_12_monthsOnce or twice a month           3.067      7.753
##                                                         t value Pr(&gt;|t|)    
## (Intercept)                                               4.922 7.02e-06 ***
## average_drink_for_12_months4 - 6 times a week             1.087    0.281    
## average_drink_for_12_monthsEvery day                      1.345    0.184    
## average_drink_for_12_monthsLess often than once a month   0.291    0.772    
## average_drink_for_12_monthsOnce a week                   -0.091    0.928    
## average_drink_for_12_monthsOnce or twice a month          0.396    0.694    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.66 on 60 degrees of freedom
## Multiple R-squared:  0.0498, Adjusted R-squared:  -0.02938 
## F-statistic: 0.629 on 5 and 60 DF,  p-value: 0.6783</code></pre>
<p>The multiple linear regression model for <span class="math display">\[\hat{Y} = 30.6 + 14.07*(drink 4-6 times a week) + 17.4*(drink everyday) + 2.15 *(drink less often than once a month) - 0.85 * (drink once a week) + 3.07*(drink once or twice a month) \]</span></p>
<pre><code>## 
## Call:
## lm(formula = age_first_diagnosed_with_diabetes ~ sleep_hours + 
##     work_hours_per_week + income_12months + average_drink_for_12_months, 
##     data = health_linear)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -35.538 -14.752   1.125  12.360  30.925 
## 
## Coefficients:
##                                                          Estimate Std. Error
## (Intercept)                                              49.40844   20.42235
## sleep_hours                                              -3.20948    2.17969
## work_hours_per_week                                       0.25612    0.23065
## income_12months$15,000 to 19,999                         -6.77748   10.59315
## income_12months$20,000 to 29,999                          0.81942    9.37375
## income_12months$30,000 to 39,999                         -3.29935   10.28338
## income_12months$40,000 to 59,999                         -5.66563    9.54966
## income_12months$5,000 to 9,999                           -1.95859   10.35657
## income_12months$60,000 to 79,999                          5.51376   14.48161
## income_12monthsLess than $5,000                         -18.20293   11.06654
## average_drink_for_12_months4 - 6 times a week             8.75342   14.58795
## average_drink_for_12_monthsEvery day                      5.75883   14.11863
## average_drink_for_12_monthsLess often than once a month   0.01742    8.30977
## average_drink_for_12_monthsOnce a week                   -4.65411   10.40972
## average_drink_for_12_monthsOnce or twice a month          1.97241    8.48730
##                                                         t value Pr(&gt;|t|)  
## (Intercept)                                               2.419   0.0192 *
## sleep_hours                                              -1.472   0.1470  
## work_hours_per_week                                       1.110   0.2720  
## income_12months$15,000 to 19,999                         -0.640   0.5252  
## income_12months$20,000 to 29,999                          0.087   0.9307  
## income_12months$30,000 to 39,999                         -0.321   0.7496  
## income_12months$40,000 to 59,999                         -0.593   0.5556  
## income_12months$5,000 to 9,999                           -0.189   0.8508  
## income_12months$60,000 to 79,999                          0.381   0.7050  
## income_12monthsLess than $5,000                          -1.645   0.1061  
## average_drink_for_12_months4 - 6 times a week             0.600   0.5511  
## average_drink_for_12_monthsEvery day                      0.408   0.6851  
## average_drink_for_12_monthsLess often than once a month   0.002   0.9983  
## average_drink_for_12_monthsOnce a week                   -0.447   0.6567  
## average_drink_for_12_monthsOnce or twice a month          0.232   0.8172  
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 19.62 on 51 degrees of freedom
## Multiple R-squared:  0.1954, Adjusted R-squared:  -0.02542 
## F-statistic: 0.8849 on 14 and 51 DF,  p-value: 0.579</code></pre>
<p>The multiple linear regression model for <span class="math display">\[\hat{Y}\]</span> = 49.41 - 3.2<em>(Sleep hours) + 0.26</em>(Hours spent working per week) - 6.78<em>(Personal Income of $15,000 to $19,999) + 0.82</em>(Personal Income of $20,000 to $29,999) - 3.29<em>(Personal Income of $30,000 to $39,999) - 5.67</em>(Personal Income of $40,000 to $59,999) - 1.96<em>(Personal Income of $5,000 to $9,999) + 5.51</em>(Personal Income of $60,000 to $79,999) - 18.2<em>(Personal Income of Less than $5,000) + 8.75</em>(drink 4-6 times a week) + 5.76<em>(drink everyday) + 0.02 </em>(drink less often than once a month) - 4.65 * (drink once a week) + 1.97*(drink once or twice a month)</p>
</div>
<div id="results" class="section level2">
<h2>Results</h2>
<p>Before we begin going over the results, we must reiterate the null hypothesis of 0 (<span class="math inline">\(H_0 = 0.1\)</span>). Our null hypothesis states the slope of the age first diagnosed with diabetes and any of the other factors have a slope of 0. This means these two variables have no affect with each other.</p>
<p>To begin, we will look at the results found in the first linear regression of “Hours spent sleeping each night vs Age first diagnosed with diabetes (Fig.1)” From this model we can see that our regression line is clearly sloping downwards. From this graph the result we have shown is clear that the more sleeping hours an individual receives each night, the lower their age is when they were first diagnosed with diabetes. Furthermore, the slope we have discovered which justifies this result is -3.46. To continue, our results have shown a discovery of the p-value of 0.0754. This is extremely important as a result of our p-value being so small and less than the null hypothesis we can say that we are successful in rejecting the null hypothesis and that sleep hours does in fact influence the age an individual was first diagnosed with diabetes.</p>
<p>Our next linear regression is “Hours spent working per week vs Age first diagnosed with diabetes (Fig.2).” From this model we can see a linear regression sloping upwards. This tells us that the more hours an individual works in a given week, the age of their first diagnosis with diabetes increases. The slope our model has shown us is 0.3176. This slope helps to justify our interpretation, a positive slope matches with the idea the age an individual is first diagnosed with diabetes increases. Moving on, we will discuss the p-value of 0.09287. Once again, this p-value is extremely small and much smaller than our null hypothesis. This means that we are successful in rejecting the null hypothesis once again. This is is our evidence that the work hours per week plays a role in influencing the age an individual is first diagnosed with diabetes.</p>
<p>The third linear regression we will be taking a look at is “Personal income during past 12 months vs Age first diagnosed with diabetes(Fig.3)”. This is a rather unique linear regression compared with our previous two as the regression line for this plot is on the flatter side. We see that the data points are scattered all over the place and there is clearly no trend. The intercept we have found is 37.5 years. This is the average age we see for an individual first diagnosed with diabetes. The income bracket 10,000 to 14,999 has no slope present. This means that the average age an individual is first diagnosed with diabetes for that group is the regular intercept of 37.5 years. In all other years we take the slope and add it to the intercept to find the average age an individual in that bracket. For example, we see that the income bracket of 15,000 to 19,999 has an average age of 33 years for their first diagnoses of diabetes. We notice that many of the income brackets have an average age like this. An interesting to note is that the income bracket of 60,000 to 79,999 has a very high average age of first diagnoses of about 48.3 years. Moving on, The p-values we have discovered from our data are almost all very large and much greater than 0.1. This means that we must accept the null hypothesis and that the income in 12 months and the age an individual is first diagnosed with diabetes have no relation with each other. Similar to what was mentioned in the abstract. Although there is one income bracket in which we are successful in rejecting the null hypothesis. This income bracket is: less than $5,000. This means that within this income bracket and the age an individual is first diagnosed with diabetes are related with one another.</p>
<p>Our final linear regression we have explored is “Average amount of alcoholic beverages drank vs Age first diagnosed with diabetes (Fig.4)”. This model is similar to that of Fig. 3 in that we do not immediately see a clear relationship. Here we see that the intercept estimate is 30.6 years. This estimate corresponds with the group that drinks 2 - 3 times a week. Similar as before we take the intercept and add the slope to it to discover the average age an individual is first diagnosed with diabetes. We have discovered that those who drink everyday have the highest average diagnoses age of 48 while those who drink once a week have the lowest average diagnoses age of 29.75 years. Moving forward with the p-value, we have discovered some extremely large p-values. These p-values are clearly much larger than 0.1 and it is evident that we must accept the null hypothesis meaning that alcohol consumption and the age an individual is first diagnosed with diabetes have no relation with one another.</p>
</div>
<div id="discussion" class="section level2">
<h2>Discussion</h2>
</div>
</div>
<div id="weaknesses" class="section level1">
<h1>Weaknesses</h1>
<p>When looking through the study, data, and analysis there are two clear weaknesses that we believe are quite notable.</p>
<p>To begin, the first weakness was from the data that we cleaned and filtered. When looking at our data, we have made slight modifications to all the columns. For example, the the “age first diagnosed with diabetes” column has been slightly adjusted to exclude all the values which correspond to labels which do not accurately portray an age. For example. The age values 96 to 99 will not be included since they correspond to those values which are never diagnosed, not applicable, do not know, and not stated; in their respective order. Furthermore, this type of cleaning and filtering has been continued down for other columns including work hours per week, sleep hours, income in the last 12 months, and average number of drinks in the last 12 months. As a result of all of this, our data has been significantly decreased from the original quantity we received from CHASS.</p>
<p>To continue, the other weakness lies with outliers. Throughout our models, it is clear that there are many outliers within our data. This weakness has a major impact on the linear regression models because the outliers influence the slopes by raising/lowering them. The other models are still influenced as well. If we removed the outliers, our models would be cleaner and much more accurate.</p>
</div>
<div id="next-steps" class="section level1">
<h1>Next Steps</h1>
<p>Overall, we believe our team has done an excellent analysis of this topic but we believe there are some further steps we can take to solidify our findings. Moving forward another step we can take is to further delve into how this data was retrieved. For example, learning about how this data was collected and the means of whom it is from. We are sure this data is not a census from every Canadian in 1991 but we believe if we further understood where our sample came from it would help solidify the findings. To continue, we believe it is best to “redo” our study with a data set from 2020 or a more recent year. Since our data is from over 20 years ago, there is a chance that our regressions have changed and it would be best to have our report with the most accurate results.</p>
<div id="conclusion" class="section level2">
<h2>Conclusion</h2>
<p>Looking back the original goal of our study was to help individuals discover diabetes earlier. The means for this was based on the variables of lifestyle habits. We have used frequentest statistics and have created linear models to show the relationships of sleep hours, work hours per week, income in 12 months, and average alcoholic consumption in 12 months with the average age an individual is diagnosed with diabetes. Our results have shown which variables have a relationship with the age of first diagnosis and which variables we had to accept the null hypothsis of <span class="math inline">\(H_0 = 0.1\)</span>. Moving forward, we have found the slopes of these relationship and the p-values. We believe our study has helped enforce our original goal as anyone utilising our findings may be more cautious with their lifestyle choices.</p>
</div>
<div id="references" class="section level2">
<h2>References</h2>
<p>Hadley Wickham and Mara Averick and Jennifer Bryan and Winston Chang and Lucy D’Agostino McGowan and Romain FranÃ§ois and Garrett Grolemund and Alex Hayes and Lionel Henry and Jim Hester and Max Kuhn and Thomas Lin Pedersen and Evan Miller and Stephan Milton Bache and Kirill MÃ¼ller and Jeroen Ooms and David Robinson and Dana Paige Seidel and Vitalie Spinu and Kohske Takahashi and Davis Vaughan and Claus Wilke and Kara Woo and Hiroaki Yutani. “Welcome to the {tidyverse}” Journal of Open Source Software, vol. 4, no. 43, pp. 1686, doi. 10.21105/joss.01686</p>
<p>Firke, Sam. “janitor: Simple Tools for Examining and Cleaning Dirty Data”, R package version 2.0.1, 2020,
(<a href="https://CRAN.R-project.org/package=janitor" class="uri">https://CRAN.R-project.org/package=janitor</a>)</p>
<p>Wickham, Hadley. “ggplot2: Elegant Graphics for Data Analysis”, Springer-Verlag New York, 2016. isbn 978-3-319-24277-4,
<a href="https://ggplot2.tidyverse.org" class="uri">https://ggplot2.tidyverse.org</a></p>
<p>Hadley Wickham and Romain FranÃ§ois and Lionel Henry and Kirill MÃ¼ller. “dplyr: A Grammar of Data Manipulation” , R package version 1.0.2, 2020,
<a href="https://CRAN.R-project.org/package=dplyr" class="uri">https://CRAN.R-project.org/package=dplyr</a></p>
<p>Paul-Christian BÃ¼rkner, “An R Package for Bayesian Multilevel Models Using Stan.” The R Journal, 2017. isbn 395-411, doi 10.18637/jss.v080.i01.</p>
<p>General social surveys, “General social survey on health”. Computing in the Humanities and Social Sciences, Faculty of Arts &amp; Science, University of Toronto.
<a href="http://www.chass.utoronto.ca/" class="uri">http://www.chass.utoronto.ca/</a></p>
<p>“The R Project for Statistical Computing”,
<a href="https://www.r-project.org/" class="uri">https://www.r-project.org/</a></p>
<p>Wu, Changbao and Mary E. Thompson, “Sampling Theory and Practice”, Springer</p>
<p>World Health Organization. “Diabetes” 2020 Jun 08.
<a href="https://www.who.int/news-room/fact-sheets/detail/diabetes" class="uri">https://www.who.int/news-room/fact-sheets/detail/diabetes</a></p>
<p>Ritchie, Hannah and Roser, Max. “Causes of Death”. Our World in Data. 2019 December.
<a href="https://ourworldindata.org/causes-of-death#" class="uri">https://ourworldindata.org/causes-of-death#</a>:~:text=Cardiovascular%20diseases%20are%20the%20leading,second%20biggest%20cause%20are%20cancers</p>
<p>Mayo Clinic. “Type 2 Diabetes”. 2020
<a href="https://www.mayoclinic.org/diseases-conditions/type-2-diabetes/diagnosis-treatment/drc-20351199" class="uri">https://www.mayoclinic.org/diseases-conditions/type-2-diabetes/diagnosis-treatment/drc-20351199</a></p>
</div>
</div>
